/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime false` (hash: c8c0b0f34c710b5a9c1f170693494d86)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env {
		CACHE: KVNamespace;
		VIDEOS: R2Bucket;
		LOGS: R2Bucket;
		DB: D1Database;
		UPLOAD_QUEUE: Queue;
		ASSETS: Fetcher;
		ENCRYPTION_KEY: string;
		NEXTAUTH_SECRET: string;
		NEXTAUTH_URL: string;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
